### ISSUE TITLE
cleaning cursor slot fails

### ISSUE THREAD

**Issue by DdaannnRU** [gaucho-matrero/altoclef#260]
## Steps to Reproduce (as best as you can)
run @gamer until full inventory
## Expected Behavior
clean the slot
## Actual Behavior (What lead to the bot getting permanently stuck)
stuck between two blocks
## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_
https://user-images.githubusercontent.com/88767403/163722353-414e006b-a1b6-4e12-809c-34deda04cef3.mp4
### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by JamesGreen31** [comment]
Edit: scaled the issue 

Yea I noticed this in my testing last night. It seems like the throw item away code isn't working right. I will keep you updated once I start work on fixing this.

**Comment by JamesGreen31** [comment]
I think this is fixed? Can you try this again for me?

**Comment by drmcbride1** [comment]
This is not solved I just made an issue to what i think it this exact problem. I detail this is a issue when your bot is on a server not a local world (although it may only apply when the server is not running over lan either, could be ping related).

**Comment by codemaker4** [comment]
This is still happening in single player for me.

**Comment by markpaul099** [comment]
Having the same problem with @codemaker4
